### ISSUE TITLE
Implement parser for PGQL

### ISSUE THREAD

**Issue by gozssky** [vescale/zgraph#1]
## Introduction

PGQL is an SQL-based query language for the property graph data model that allows you to specify high-level graph patterns which are matched against vertices and edges in a graph. The language is designed to be intuitive and easy to learn, and it is also expressive enough to support a wide range of graph queries.

## Implementation

The implementation is based on the [PGQL 1.5 Specification](https://pgql-lang.org/spec/1.5/).

**Comment by gozssky** [comment]
@lonng, I will work on implementing the parser for PGQL in the next several weeks.

**Comment by lonng** [comment]
@gozssky I have implemented the basic framework of the PGQL parser and left the actions empty. See https://github.com/vescale/zgraph/commit/ea74fd2d6bfb617ba2918f7d3588d6837970e54b

**Comment by lonng** [comment]
@gozssky Basically, I want to define the schema with strong type (performance / type inference), which will be different from PGQL. I define the parser with traditional `CREATE VERTEX/EDGE TABLE` way just for start this work quickly.

Actually, I have no idea how to define the schemas of vertex and edges so far, and the `UPDATE/DELETE/INSERT` syntax should change also.

Have you some idea about this? Do you want we follow PGQL strictly?

**Comment by gozssky** [comment]
I prefer to follow PGQL strictly so that we don't need to spend time advertising our special syntax. With the influence of Oracle, users are more likely to have a try on our product.

In terms of strong or weak schema, from my previous PGQL implementation on TiDB, strong schema would bring more complexity to the system, and performance is likely to be worse than weak schema.

Suppose we have a query like `(n)-[e]->(m)`. If we have strong schema, n, e, m may have more than one schema, the final number of combinations is huge.

Graph queries mainly focus on vertices and edges. Any two vertices can be connected by multiple edges, and the vertices and edges can have multiple properties. The schema is hard to be defined in advance, and the schema is likely to be changed frequently.

**Comment by gozssky** [comment]
@lonng I have almost finished the PGQL query syntax in https://github.com/gozssky/tidb-1/blob/graph/parser/parser.y#L14253-L14606. If you intend to further implement the parser, the code snippet can be a reference.

**Comment by lonng** [comment]
Got, please move them to the zgraph/parser, thanks.

**Comment by lonng** [comment]
Finished in https://github.com/vescale/zgraph/commit/76a375df6aae900caf5da538637eb0e82db00de2

**Comment by gozssky** [comment]
Good job! I'm going to close this issue.
