### ISSUE TITLE
The method CurrentGraph() of stmtctx.Contex should return catalog.Graph object

### ISSUE THREAD

**Issue by lonng** [vescale/zgraph#10]
Currently, the method CurrentGraph() of stmtctx.Contex should return a string, and it's better to return graph object directly.

**Comment by tanqiangyes** [comment]
[fix: references CurrentGraph](https://github.com/vescale/zgraph/pull/12) this pr fix some compile error.

**Comment by gozssky** [comment]
Closed by https://github.com/vescale/zgraph/pull/11, https://github.com/vescale/zgraph/pull/12
