### ISSUE TITLE
Replace sync.WaitGroup with https://github.com/sourcegraph/conc

### ISSUE THREAD

**Issue by lonng** [vescale/zgraph#14]
[Replace sync.WaitGroup with https://github.com/sourcegraph/conc ](https://github.com/sourcegraph/conc) provides more convenient manner to run parallel tasks.

Reference README of the `conc` package.

**Comment by lonng** [comment]
Anyone interested in this issue?
There are 8 usages in the zgraph repo. see: https://sourcegraph.com/search?q=context:global+repo:github.com/vescale/zgraph+waitgroup&patternType=standard&sm=1

**Comment by Rishav1707** [comment]
Shall I work on this issue? @lonng

**Comment by lonng** [comment]
@Rishav1707 of course. Go ahead, thanks.
