### ISSUE TITLE
Define all parser AST nodes

### ISSUE THREAD

**Issue by lonng** [vescale/zgraph#2]
Currently, only the PGQL spec syntax was defined and left all AST constructive actions empty. The next step is to implement all of them.

TODO:
- [ ] Basic classes of statement/expr node
- [ ] Select statement related nodes
- [ ] Update statement related nodes
- [ ] Delete statement related nodes
- [ ] Insert statement related nodes
- [ ] Create graph/index related nodes

**Comment by tanqiangyes** [comment]
in parser/ast， just add node?

**Comment by lonng** [comment]
@tanqiangyes Thanks for you for interesting in zGraph project.

Yes, you can implement where have `TODO implement me`.

**Comment by tanqiangyes** [comment]
Is there some documentation on the corresponding requirements, the end result, and the testing methods?

**Comment by lonng** [comment]
@tanqiangyes Currently, this project is in the early stage, and there is no more documentation except comments in the code.  Only some unit tests for the core module.
