### ISSUE TITLE
Add zgraph binary for deugging

### ISSUE THREAD

**Issue by lonng** [vescale/zgraph#8]
It's better to provide an individual zgraph binary to support interact with zgraph database.
I think we can create a new binary and place it into `$ROOT/cmd/zgraph`.

**Comment by lonng** [comment]
I added the initial code: https://github.com/vescale/zgraph/tree/main/cmd/zgraph

**Comment by tanqiangyes** [comment]
Are there any other questions on this issue? If there are, please point them out, if not, please close it, thanks. @gozssky
